In [4]:
import numpy as np

def gauss_elimination(A, b):
    n = len(b)
    for i in range(n):
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j] = A[j] - factor * A[i]
            b[j] = b[j] - factor * b[i]
            print(A)
    
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x

def lu_decomposition(A, b):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    
    for i in range(n):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            U[j] = U[j] - factor * U[i]
            L[j, i] = factor
    
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x


K1, K2, K3, K4, K5 = 11.0, 20.0, 20.0, 20.0, 90.0  # K1 is last three digits of roll number
A = np.array([[K1 + K2 + K3, -K2, -K3],
              [-K2, K2 + K4, -K4],
              [-K3, -K4, K3 + K4 + K5]])

r = np.array([20.0, 20.0, 20.0])

# Gauss Elimination
x_gauss = gauss_elimination(A.copy(), r.copy())
print("Solution using Gauss Elimination:", x_gauss)

# LU Decomposition
x_lu = lu_decomposition(A, r)
print("Solution using LU Decomposition:", x_lu)


[[ 51.         -20.         -20.        ]
 [  0.          32.15686275 -27.84313725]
 [-20.         -20.         130.        ]]
[[ 51.         -20.         -20.        ]
 [  0.          32.15686275 -27.84313725]
 [  0.         -27.84313725 122.15686275]]
[[ 51.         -20.         -20.        ]
 [  0.          32.15686275 -27.84313725]
 [  0.           0.          98.04878049]]
Solution using Gauss Elimination: [1.11940299 1.32462687 0.52985075]
Solution using LU Decomposition: [1.11940299 1.32462687 0.52985075]
